### ISSUE TITLE
Importing mp3

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/torchaudio#39]
Hi,
with R Version 4.1.2, I cannot use the tuneR_loader on an mp3 anymore. 
"Error in system("mp3splt -h", intern = TRUE) : 'mp3splt' not found"
Installation however is not possible, since 
"package ‘mp3splt’ is not available for this version of R".

Maybe its a topic for torchaudio, maybe its rather an issue for mp3splt. I wanted to post this here to raise the awareness in any case.
Thanks!

**Comment by skeydan** [comment]
Sorry for the very late response! We've recently refactored how audio loading works in `torchaudio` (see NEWS.md for 0.3.1, and/or the updated README).
If you're still interested, you might want to try the new implementation :-)
I'm closing this issue, but please feel free to open a new one should you run into any problems.
